spring.application.name=productService
server.port=8081

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${SPRING_DATA_URL}
spring.datasource.username=${SPRING_DATA_USERNAME}
spring.datasource.password=${SPRING_DATA_PASSWORD}
spring.jpa.show-sql=true

auth.jwt.secret=${JWT_SECRET}
auth.jwt.expiration=${JWT_EXPIRATION:900000}