spring.application.name=productService
server.port=8081

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${SPRING_DATA_URL}
spring.datasource.username=${SPRING_DATA_USERNAME}
spring.datasource.password=${SPRING_DATA_PASSWORD}
spring.jpa.show-sql=true

auth.jwt.secret=${JWT_SECRET}
auth.jwt.expiration=${JWT_EXPIRATION:900000}

#Eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://AuthService/oauth2/jwks}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER:http://localhost:8080}