spring.application.name=notificationService

server.port=8085

# Kafka Address
spring.kafka.bootstrap-servers=localhost:9092

#Eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/