spring.application.name=orderService

server.port=8083

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${SPRING_DATA_URL}
spring.datasource.username=${SPRING_DATA_USERNAME}
spring.datasource.password=${SPRING_DATA_PASSWORD}
spring.jpa.show-sql=true


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://AuthService/oauth2/jwks}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER:http://localhost:8080}

#-----------------------------------
#Client
#1 Registration Details
spring.security.oauth2.client.registration.order-service-client.client-id=orderService
spring.security.oauth2.client.registration.order-service-client.client-secret=orderservice@26
spring.security.oauth2.client.registration.order-service-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.order-service-client.scope=system


spring.security.oauth2.client.registration.order-service-client.provider=my-auth-server
#2 Provide details: Where to get new token
spring.security.oauth2.client.provider.my-auth-server.token-uri=http://localhost:8080/oauth2/token
#___________________________________



#Eureka client
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/